version: "3"
services:
  influxdb:
    environment:
      INFLUXDB_ADMIN_USER: dev
      INFLUXDB_ADMIN_PASSWORD: dev
      INFLUXDB_ADMIN_ENABLED: "true"
    image: influxdb:latest
    ports:
      - "8086:8086"
      - "8083:8083"
    volumes:
      - /tmp/influxdb:/var/lib/influxdb
    networks:
      - transactions-app
  application:
    image: application:latest
    ports:
      - "8080:8080"
    depends_on:
      - influxdb
    networks:
      - transactions-app
  application-load:
    image: application-load:latest
    ports:
      - "8081:8081"
    depends_on:
      - application
    networks:
      - transactions-app
networks:
  transactions-app:
    driver: bridge